name: CI

on: [push]
env:
  XDEBUG_MODE: coverage
jobs:
  build-74:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Composer
        uses: php-actions/composer@v6
        with:
          php_version: "7.4"
      - name: PHP Unit
        uses: php-actions/phpunit@v3
        with:
          version: 9
          php_version: "7.4"
          php_extensions: xdebug
          args: --coverage-clover=coverage.xml
  build-82:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Composer
        uses: php-actions/composer@v6
        with:
          php_version: "8.2"
      - name: PHP Unit
        uses: php-actions/phpunit@v3
        with:
          version: 9
          php_version: "8.2"
          php_extensions: xdebug
          args: --coverage-clover=coverage.xml
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
